# Generated by Django 6.0.6 on 2026-07-01 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Лого бренду')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='URL ідентифікатор')),
            ],
            options={
                'verbose_name': 'Головна категорія одягу',
                'verbose_name_plural': 'Головні категорії одягу',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип одягу')),
                ('slug', models.SlugField(unique=True, verbose_name='URL ідентифікатор')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.maincategory')),
            ],
            options={
                'verbose_name': 'Підкатегорія одягу',
                'verbose_name_plural': 'Підкатегорії одягу',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Модель товару')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Фото товару')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_of_product', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalog.subcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['name', 'price'],
            },
        ),
    ]
