name: Django CI

on:
  push:
    branches: [ "main", "master", "shop_dev" ]
  pull_request:
    branches: [ "main", "master", "shop_dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: ankane/pgvector:v0.5.1
        env:
          POSTGRES_DB: shop_modivo_db
          POSTGRES_USER: modivo_user
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linters
      run: |
        pip install flake8
        # Шукаємо тільки критичні синтаксичні помилки
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Tests
      env:
        SECRET_KEY: "temporary-ci-secret-key"
        DEBUG: "True"
        DB_NAME: "shop_modivo_db"
        DB_USER: "modivo_user"
        DB_PASSWORD: "supersecret"
      run: |
        PGPASSWORD=supersecret psql -h localhost -U modivo_user -d shop_modivo_db -c "CREATE EXTENSION IF NOT EXISTS vector;"
        pytest